### PR TITLE
Fix betterolls templates

### PR DESCRIPTION
**Pull request by DarKDinDoN**
Hey,

Took a shot a making this compatible with BetterRolls.
Let me know what you think of this.

Also fixed a couple of errors on items that don't have duration.

Made a lot of tests with & without BetterRolls.
No errors so far :)

### CODE REVIEW

**Comment by bitkiller0** [comment]
Thanks for looking into this.  I like the changes for items with missing duration.  That should have been included from the get-go; sorry to have missed that.  Unfortunately, I can't just merge your pull request, as I have other changes in-flight that may affect this; I'll have to check that first.

The changes for better rolls I'm not so sure about.  It breaks the paradigm of how DND5E and SIFToolkit work.  SIFToolkit is designed for DND5E to pull the info from a roll, not from a chat.  Doing it in two places is not really a direction that I want to go.  Also, this sort of fix also causes problems with the message history recording non-actionable messages.  Time allowing, I'll install better rolls and look into making them work together.  Unfortunately, I don't have a TON of free time over the next few days.  

You are, by all means, welcome to use your changes on your system.  I will let you know as I make changes.

**Comment by DarKDinDoN** [comment]
@bitkiller0 Alright here is another try, then I cave :)
Tried to not store chat message ids when not needed (no duration and no target, meaning non-actionable messages)

---

One thing I don't understand, tho.

> SIFToolkit is designed for DND5E to pull the info from a roll, not from a chat. Doing it in two places is not really a direction that I want to go.

Sorry if I'm mistaken, but that doesn't seem to be entirely true.
These lines are pulling the html template from a chat message to detect a button. I don't see any roll parsing here:
- https://github.com/bitkiller0/SIFToolkit/blob/main/scripts/dnd5e/Hooks.js#L46
- https://github.com/bitkiller0/SIFToolkit/blob/main/scripts/dnd5e/Hooks.js#L56

Remove these two little chat parsers, and nothing work anymore, because those are not just hijacking the buttons but also actioning the message history recording at: https://github.com/bitkiller0/SIFToolkit/blob/main/scripts/dnd5e/Utils.js#L84

I believe that is why this is not working with BetterRolls. Because BetterRolls never outputs a "Place Measured Template" in the chat message.
And when the chat message doesn't display a "Damage" button as well (because no damage declared on the item), then SIF is not picking up at all (because there are no buttons to parse).

**Review by bitkiller0 — APPROVED** [review]

**Comment by DarKDinDoN** [comment]
@bitkiller0 what happened? You merged, then deleted the code?

**Comment by bitkiller0** [comment]
Yes. I tried to merge part of it but merge the whole thing. I fixed it.

**Comment by DarKDinDoN** [comment]
@bitkiller0 ok, it happens, I guess.

Do you have a comment on this? https://github.com/bitkiller0/SIFToolkit/pull/12#issuecomment-890197119
And my last commit ? If only to get your opinion on that.

Rest assured, I won't bother you anymore after that. I stand by my comment.
Also, because I'm not quite enjoying seeing my fork called "bad" openly on discord.

**Comment by bitkiller0** [comment]
First: I apologize for calling the fork bad.  It's not what I meant.  I clarified as much on discord.  Regardless, it's not cool; you are right, and I am sorry.

Second: Let me comment with this:  I don't like a blanket else statement where you put it; too much unpredictability.  I don't want too much heavy lifting and manipulation of data done inside of a Hook; I'm already upset with how much of that *I* am doing, and it's on my list of things to correct.  Your attempt to correct the inappropriate storing of chat message data for non-related chats did even more of that.  Last, as sort-of an extension/explanation of the first point: your fix was specific to your use case.  I can foresee situations where OTHER things could be entered into the chat that could have different effects. 

Last: Support for better rolls is very low on my priority list, and I may reject changes if I feel that they are moving contrary to my current plans.  

I hope that gives you what you're looking for.

**Comment by DarKDinDoN** [comment]
@bitkiller0 Fair point. Thx for the apologies.
Keep up the good work.

**Comment by bitkiller0** [comment]
I'm trying to take another look at this, and reconsidering your strategy.  I'm curious though...  when I install better Rolls, the template borders and other animations supplied by SIFT fail to work for me.  Are they still working for you?  It seems that for some reason, it seems that better rolls is delaying the template creation, so the template is not present when SIFT ASYNCHRONOUSLY attempts to update the template.  I'm GUESSING that Better Rolls is inserting itself into that stack somewhere.

**Comment by bitkiller0** [comment]
NM.  It's because I'm looking for the data to be in the chat data.  Hence why your code worked.  Let me see if I can find a place that I want to put this.

**Pull request merged**
